//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Play"",
            ""id"": ""b7b6675d-a933-4edf-972f-c9da2e1b2851"",
            ""actions"": [
                {
                    ""name"": ""Select Piece"",
                    ""type"": ""Button"",
                    ""id"": ""7973eb63-7f6e-4500-a1a0-6653ea37f293"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Tile"",
                    ""type"": ""Button"",
                    ""id"": ""cfa1a7ab-e5b6-45d9-a7ab-5e323ea2fc35"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""566f9596-e6b3-4f8a-a993-42b895577c89"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Piece"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd5f0936-f71b-4449-8da7-dbc5a717b4c3"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Tile"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Play
        m_Play = asset.FindActionMap("Play", throwIfNotFound: true);
        m_Play_SelectPiece = m_Play.FindAction("Select Piece", throwIfNotFound: true);
        m_Play_SelectTile = m_Play.FindAction("Select Tile", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Play
    private readonly InputActionMap m_Play;
    private IPlayActions m_PlayActionsCallbackInterface;
    private readonly InputAction m_Play_SelectPiece;
    private readonly InputAction m_Play_SelectTile;
    public struct PlayActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectPiece => m_Wrapper.m_Play_SelectPiece;
        public InputAction @SelectTile => m_Wrapper.m_Play_SelectTile;
        public InputActionMap Get() { return m_Wrapper.m_Play; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayActions set) { return set.Get(); }
        public void SetCallbacks(IPlayActions instance)
        {
            if (m_Wrapper.m_PlayActionsCallbackInterface != null)
            {
                @SelectPiece.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnSelectPiece;
                @SelectPiece.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnSelectPiece;
                @SelectPiece.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnSelectPiece;
                @SelectTile.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnSelectTile;
                @SelectTile.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnSelectTile;
                @SelectTile.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnSelectTile;
            }
            m_Wrapper.m_PlayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SelectPiece.started += instance.OnSelectPiece;
                @SelectPiece.performed += instance.OnSelectPiece;
                @SelectPiece.canceled += instance.OnSelectPiece;
                @SelectTile.started += instance.OnSelectTile;
                @SelectTile.performed += instance.OnSelectTile;
                @SelectTile.canceled += instance.OnSelectTile;
            }
        }
    }
    public PlayActions @Play => new PlayActions(this);
    public interface IPlayActions
    {
        void OnSelectPiece(InputAction.CallbackContext context);
        void OnSelectTile(InputAction.CallbackContext context);
    }
}
